authzed/api

- authzed/api/v1/watch_service.proto
The changes herein add support to the v1.WatchService.Watch API that allows for a client to watch for changes optionally filtered by one or more object types. If the `optional_object_types` field is not specified by the client then the intention is to start a watch over all object types.
These changes are to support the work that in underway in https://github.com/authzed/spicedb/pull/255 and https://github.com/authzed/spicedb/pull/263 and as proposed in the new LookupWatch API that is under active discussion and development in https://github.com/authzed/spicedb/issues/207.
I recognize these changes are breaking, so I'm open to alternatives, but seeing as there is not yet a v1.WatchService.Watch API implementation (it is under active PR as referenced above) I don't these these breaking …
> Add support to Watch all object types 

- authzed/api/v0/core.proto
- authzed/api/v0/namespace.proto
- authzed/api/v1/core.proto
See https://github.com/authzed/spicedb/issues/1
> API changes in preparation for wildcard (public) support

- authzed/api/v1alpha1/watchresources_service.proto
This work is part of the effort behind this [issue](https://github.com/authzed/spicedb/issues/207).
> feat: add WatchResourcesService to `v1alpha1` package

- authzed/api/v0/core.proto
- authzed/api/v1/core.proto
It was not properly checking that the *entire* ID matches the regex
Fixes https://github.com/authzed/spicedb/issues/407
> Strengthen the validation regexs on object IDs

- authzed/api/v0/acl_service.proto
- authzed/api/v0/namespace_service.proto
- authzed/api/v0/watch_service.proto
Adds deprecations to v0 proto files using the findings below to provide the most granular notice in generated code.
Result of `deprecated = true` in generated code
| Client | rpc | message | file |
| ----------------| --- | ---------- | --- |
| go | deprecation comment | deprecation comment | deprecation comment | 
| python | none | none | none |
| node | `@deprecated` |`@deprecated` |`@deprecated` on file |
| java | none | `@java.lang.Deprecated` | `@java.lang.Deprecated` on classes |
| ruby | none | none | none |
> Mark v0 protos with deprecations

- .github/workflows/lint.yaml
- README.md
- authzed/api/v1/permission_service.proto
This clarifies the atomicity of WriteRelationships and runs the other comments through a grammar check.
> v1: update permission services docstrings

- authzed/api/v1/permission_service.proto
The previous wording ("one or more filters") made it sound like `relationship_filter` should have been `repeeated`, but that's not the way the service is implemented. The new wording more closely reflects the behavior of the endpoint.
Documentation wording
Review.
> Fix documentation of DeleteRelationships

- authzed/api/v1/core.proto
Part of https://github.com/authzed/spicedb/issues/836
`Relationships` can be caveated through a `ContextualizedCaveat`. This is a reference to the identifier of a caveat, and a caveat context, which is a key-value structure fed into the caveat evaluation engine.
> introduce caveat in API

- authzed/api/v1/permission_service.proto
Part of https://github.com/authzed/spicedb/issues/881
Part of https://github.com/authzed/spicedb/issues/882
Part of https://github.com/authzed/spicedb/issues/880
this makes it possible for clients to provide context for caveat evaluation at request time.
This context will be injected at evaluation time and influence the evaluation result.
> introduce caveat context in PermissionService

- authzed/api/v1/error_reason.proto
Will be used if the client sends a parameter value for a caveat that cannot be converted to the expected type
> Add an error reason for caveat parameter type errors

- authzed/api/v1/permission_service.proto
This is necessary because exclusions on wildcards can themselves also be caveated
> Update API response for LookupSubjects to handle caveats on exclusions

- authzed/api/v1/debug.proto
This will allow debug traces to show the caveat's name as well, where applicable
> Add caveat name to debug info for caveat eval

- authzed/api/v1/watch_service.proto
Fixes https://github.com/authzed/spicedb/issues/1168
> Add documentation to clarify optional_start_cursor in watch API

- authzed/api/v1/core.proto
- authzed/api/v1/error_reason.proto
- authzed/api/v1/permission_service.proto
Remains backwards compatible because the new fields are optional on the request
> Add support for cursors to LookupResources

- authzed/api/v1/error_reason.proto
if any of the relationships in a WriteRelationship request exceed a configured server limit for the caveat context, the server will fail with
`ERROR_REASON_MAX_RELATIONSHIP_CONTEXT_SIZE`
> add max relationship context size error

- .github/workflows/lint.yaml
- .github/workflows/release.yaml
I need to test this, but the idea is that every commit gets push as a draft and only releases will be published as tags, which move forward the documentation etc...
> buf: push everything but releases as drafts

- .github/workflows/lint.yaml
This defaults to the ref (e.g. "main").
"main" is explicitly not allowed by drafts.
> .github: explicitly name draft

- .github/workflows/lint.yaml
The buf push action only uses github.ref_name and no sha for drafts, which is incompatible with pushing things from main.
> .github: manually buf push

- authzed/api/v1/experimental_service.proto
Introduces Bulk Check API, which allows issuing multiple CheckPermission requests at once
considerations:
- does not reuse CheckPermissionRequest nor Response because a bulk check call requires a single consistency level and returns a single checked at zedtoken
- gRPC map type does not support messages as key, so a repeated pair message is created
- the response are pair items that include the request and the corresponding response
- two different APIs are introduced: one that streams responses as they are computed, and another one that blocks until all checks are completed. A client-streaming version was discarded for now.
> introduces bulk check permission API

- .github/workflows/manual-client-update.yaml
Starting with authzed-node and, if this works, will add the other client libs
> Add manual workflow for kicking off updates in client libs

- authzed/api/v1/error_reason.proto
to support https://github.com/authzed/spicedb/pull/1552
Database serialization errors are not that uncommon when running the backend datastores at isolation level `SERIALIZABLE`. However, those errors could be reported in a clearer way to the client instead of some cryptic database error.
This adds a new error reason to support providing a typed response when serialization errors happen.
> add serialization error

- authzed/api/v1/error_reason.proto
- authzed/api/v1/experimental_service.proto
- authzed/api/v1/permission_service.proto
The `BulkCheckPermission` API is stable and can be promoted into the v1 `PermissionsService`.
Resolves #92
> Promote `BulkCheckPermission` to v1

- .github/workflows/release.yaml
the buf github action does not support
configuring the tag to be pushed, so it
always defaults to pushing the github SHA.
This changes the action to push the tag
to BSR with the ref_name instead of the commit
SHA.
see https://github.com/authzed/api/actions/runs/8331581711/job/22798794304
Also see https://github.com/bufbuild/buf-push-action/issues/20#issuecomment-1944362672 for future changes on this topic, the buf team will be introducing some changes to help here
> fix buf push tag on release

- .github/workflows/lint.yaml
- authzed/api/v1/core.proto
- authzed/api/v1/debug.proto
- authzed/api/v1/error_reason.proto
- authzed/api/v1/experimental_service.proto
- authzed/api/v1/openapi.proto
- authzed/api/v1/permission_service.proto
- authzed/api/v1/schema_service.proto
- authzed/api/v1/watch_service.proto
- buf.yaml
Fixes https://github.com/authzed/authzed-java/issues/80
Tweaks the proto java output to have more ergonomic class names.
As a consequence, all types become top-level classes without nested outer classes.
E.g. `ExperimentalServiceOuterClass.BulkImportRelationshipsResponse` becomes `BulkImportRelationshipsResponse`
The generated output proto is less verbose, but clients will have to update their code accordingly. Given that the `authzed-java` SDK is < 1.0.0, we consider the API surface unstable and will proceed with the change.
>From https://protobuf.dev/reference/java/java-generated/#invocation When the option java_multiple_files = true is enabled, Then the compiler will also create separate .java files for each of the classes/enums which it will generate for each top-level message, …
> generate multiple java files

- authzed/api/v1/error_reason.proto
- authzed/api/v1/experimental_service.proto
It is less powerful but removes a potential DOS vector
> Change the regexes in the experimental API to prefix matches

- authzed/api/v1/error_reason.proto
- authzed/api/v1/experimental_service.proto
This will eventually be backed by a counting/stats service, but for now will call count(*)
> Add experimental relationship count API

- authzed/api/materialize/v0/watchpermissionsets.proto
A breaking schema changes require recomputing the snapshot to rebuild the Materialize index, and in turn once this is ready, the consumer will have to rebuild their own indexes. This event is added to differentiate between "schema changed" and "index ready after schema changed" events.
> materialize: adds a new event to denote a breaking schema change

- authzed/api/materialize/v0/watchpermissionsets.proto
After the introduction of BreakingSchemaChange,
clients will be notified that an incompatible change has happened and that they need rebuild their index. In order to do that, they need to call LookupPermissionSets with the revision at which the breaking event happened.
This introduces an optional revision in LookupPermissionSets to support this use-case.
> adds optional revision in LookupPermissionSets

- authzed/api/materialize/v0/watchpermissionsets.proto
to support backends that can directly index instead of using an offset
> add string key to materialize cursor

- .pre-commit-config.yaml
- authzed/api/v1/permission_service.proto
Part of what we want to release in 1.37.
* Move services out of experimental and rename according to scheme we used for `CheckBulkPermission`
Review. See that test steps go green.
> Move relationship bulk import and export into permissions service

- authzed/api/v1/error_reason.proto
- authzed/api/v1/experimental_service.proto
- authzed/api/v1/permission_service.proto
- authzed/api/v1/watch_service.proto
Reference: https://github.com/authzed/spicedb/issues/966
> Add API support for transaction metadata

- authzed/api/v1/experimental_service.proto
- authzed/api/v1/permission_service.proto
The entire bulk import is a single transaction, and there is no message in which we can provide the metadata, so disallow it
> Remove transaction metadata from bulk imports

- authzed/api/v1/permission_service.proto
I missed this when I was doing the work to copy ImportBulkRelationships and ExportBulkRelationships out of Experimental. This fixes this part of the openAPI generation.
Fix the paths for the new endpoints
Review.
> Fix paths for import/export bulk

- authzed/api/v1/experimental_service.proto
- authzed/api/v1/permission_service.proto
This was noted by a Discord user. The experimental service's version had this, but the permission service's version didn't, which caused confusion and had them asking whether the two versions of the service had any meaningful differences. They don't and this should help clarify that.
Copy over the extended documentation
Review.
> Update documentation of BulkImportRelationshipsRequest

- .github/workflows/release-client-update.yaml
I was wondering why `authzed-dotnet` didn't automatically PR when we released API v1.40.0 and then I remembered this action. This should mean that the next API update creates a PR.
* Add authzed-dotnet to list of triggers
Review.
> Add dotnet to list of triggers

- authzed/api/v1/core.proto
- authzed/api/v1/watch_service.proto
For https://github.com/authzed/spicedb/issues/1995
> update watch api: include schema changes

- authzed/api/v1/watch_service.proto
Amendment to https://github.com/authzed/api/pull/133
> modify watchResponse

- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- README.md
- buf.gen.yaml
- docs/apidocs.swagger.json
- magefiles/dev.go
- magefiles/go.mod
- magefiles/go.sum
Make a change to one of the protos, then commit. You should see something like this, and the swagger file should be automatically updated.
```shell
$ git commit ...
buf generate.........................................(no files to check)Skipped
buf lint.............................................(no files to check)Skipped
buf format...........................................(no files to check)Skipped
yamllint.............................................(no files to check)Skipped
[generate-openapi 4f93a2e] generate OpenAPI docs
Date: Mon May 26 16:42:39 2025 -0700
7 files changed, 3407 insertions(+), 28 deletions(-)
create mode 100644 Makefile
create mode 100755 buf.gen.yaml
create mode 100644 docs/apidocs.swagger.json
[17:02:22] ~/Documents/GitHub/api (generate-openapi) $
> generate OpenAPI docs

- authzed/api/materialize/v0/watchpermissionsets.proto
Adds the definition of the Download API to materialize v0
This is not yet implemented, but will be.
> add download api definition to materialize v0

- authzed/api/v1/watch_service.proto
Reference: https://github.com/authzed/spicedb/issues/2439
> Add a new repeated metadata field for revisions that contain multiple transactions
